a="1"
b=2
c=a+b
d={}
d["3"]={}
d["3"][1] = 2
d["3"][2] = 1

KTROBO_MESSAGE_MYMSTRUCT_SIZE = 128
KTROBO_MESSAGE_ID_ANIMATIONBUILDER_BONE_PUSHED = 1
KTROBO_MESSAGE_ID_ANIMATIONBUILDER_HON_MESH_AFTER =2
KTROBO_MESSAGE_RECEIVER_ID_SYSTEM =0
KTROBO_MESH_BONE_MAX =32

